# ==============================================================================
# MACHINE LEARNING PIPELINE
# Generated by ML Studio
# ==============================================================================
# This script contains the exact data pipeline, preprocessing, model configuration,
# training, and evaluation steps used during your session.
# Save this file as 'run_experiment.py' and ensure the dataset CSV file is placed
# in the same directory.
# ==============================================================================

# ------------------------------------------------------------------------------
# 0. Imports
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline


# ------------------------------------------------------------------------------
# 1. Load Dataset
# ------------------------------------------------------------------------------
DATASET_PATH = 'datasets/exam.csv'
print(f'Loading dataset: {DATASET_PATH}')
df = pd.read_csv(DATASET_PATH)


# ------------------------------------------------------------------------------
# 2. Feature & Target Selection
# ------------------------------------------------------------------------------
FEATURES = ['study_hours']
TARGET = 'exam_score'

X = df[FEATURES]
y = df[TARGET]


# ------------------------------------------------------------------------------
# 3. Split Strategy
# ------------------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.8, random_state=42
)


# ------------------------------------------------------------------------------
# 4. Preprocessing Pipeline
# ------------------------------------------------------------------------------
# Feature types are detected from the training split to prevent leakage
numeric_features = list(X_train.select_dtypes(include='number').columns)
categorical_features = list(X_train.select_dtypes(include=['object', 'category', 'bool']).columns)

# Define handling strategies
numeric_imputer = 'passthrough'
categorical_imputer = 'passthrough'
encoder = 'passthrough'
scaler = 'passthrough'

# Assemble pipelines
numeric_pipeline = Pipeline(steps=[
    ('imputer', numeric_imputer),
    ('scaler', scaler)
])

categorical_pipeline = Pipeline(steps=[
    ('imputer', categorical_imputer),
    ('encoder', encoder)
])

preprocessor = ColumnTransformer(
    transformers=[
        ('numeric', numeric_pipeline, numeric_features),
        ('categorical', categorical_pipeline, categorical_features)
    ],
    remainder='drop',
    verbose_feature_names_out=False
)


# ------------------------------------------------------------------------------
# 5. Model Configuration
# ------------------------------------------------------------------------------
# Model: Linear Regression
model = LinearRegression()


# ------------------------------------------------------------------------------
# 6. Build and Fit Pipeline
# ------------------------------------------------------------------------------
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

print('Fitting pipeline on training data...')
pipeline.fit(X_train, y_train)
print('Training complete.')

y_train_pred = pipeline.predict(X_train)
y_test_pred = pipeline.predict(X_test)



# ------------------------------------------------------------------------------
# 7. Evaluation Metrics
# ------------------------------------------------------------------------------
r2 = r2_score(y_test, y_test_pred)
mse = mean_squared_error(y_test, y_test_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_test_pred)
mape = mean_absolute_percentage_error(y_test, y_test_pred) * 100

print('\n' + '=' * 40)
print('EVALUATION METRICS (Train-Test Split)')
print('=' * 40)
print(f'R^2 Score: {r2:.4f}')
print(f'RMSE:      {rmse:.4f}')
print(f'MAE:       {mae:.4f}')
print(f'MAPE:      {mape:.2f}%')
print('=' * 40)


# ------------------------------------------------------------------------------
# 8. Publication-Quality Plots
# ------------------------------------------------------------------------------
sns.set_theme(style='whitegrid')
plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 12,
    'axes.labelsize': 14,
    'axes.titlesize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 10,
    'figure.dpi': 150,
    'axes.grid': True,
    'grid.alpha': 0.5,
    'grid.color': 'lightgray',
    'grid.linestyle': '-'
})

# 1. Actual vs Predicted Scatter Plot
fig, ax = plt.subplots(figsize=(8, 6))
ax.scatter(y_test, y_test_pred, alpha=0.6, color='royalblue', edgecolor='k', s=70, label='Predictions')
min_val = min(y_test.min(), y_test_pred.min())
max_val = max(y_test.max(), y_test_pred.max())
ax.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='Ideal Fit (y=x)')
ax.set_xlabel('Actual exam_score')
ax.set_ylabel('Predicted exam_score')
ax.legend(loc='lower right', frameon=True, edgecolor='gray')
plt.tight_layout()
plt.savefig('actual_vs_predicted.png', dpi=300)
print('Saved plot: actual_vs_predicted.png')
plt.close()

# 2. Residual Plot
fig, ax = plt.subplots(figsize=(8, 6))
residuals = y_test - y_test_pred
ax.scatter(y_test_pred, residuals, alpha=0.6, color='royalblue', edgecolor='k', s=70)
ax.axhline(y=0, color='red', linestyle='--', linewidth=2)
ax.set_xlabel('Predicted exam_score')
ax.set_ylabel('Residual (exam_score)')
plt.tight_layout()
plt.savefig('residuals_plot.png', dpi=300)
print('Saved plot: residuals_plot.png')
plt.close()

# 3. Residual Distribution Histogram
fig, ax = plt.subplots(figsize=(8, 6))
ax.hist(residuals, bins=20, color='royalblue', edgecolor='black', alpha=0.8)
ax.set_xlabel('Residual (exam_score)')
ax.set_ylabel('Frequency')
plt.tight_layout()
plt.savefig('residuals_distribution.png', dpi=300)
print('Saved plot: residuals_distribution.png')
plt.close()

# 9. Feature Importance Plot (if supported by the model)
model_step = pipeline.named_steps['model']
if hasattr(model_step, 'feature_importances_'):
    importances = model_step.feature_importances_
    # Clean preprocessor names
    feature_names = pipeline.named_steps['preprocessor'].get_feature_names_out()
    cleaned_names = [name.replace('num__', '').replace('cat__', '') for name in feature_names]
    order = np.argsort(importances)[::-1]
    importances = importances[order]
    cleaned_names = np.array(cleaned_names)[order]

    # Keep top 20 features max
    if len(cleaned_names) > 20:
        importances = importances[-20:]
        cleaned_names = cleaned_names[-20:]

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.barh(cleaned_names[::-1], importances[::-1], color='royalblue', edgecolor='black')
    ax.set_xlabel('Feature Importance')
    ax.set_ylabel('Features')
    plt.tight_layout()
    plt.savefig('feature_importance.png', dpi=300)
    print('Saved plot: feature_importance.png')
    plt.close()
