"""
HPC Experiment Packaging
========================
Packages a complete, self-contained experiment directory containing:
1. dataset.csv
2. config.json
3. experiment.py (self-contained standalone runner generating results.json)
4. run.slurm (SLURM job submission script with Unix LF line breaks)
"""

import os
import json
import uuid
import tempfile
import pandas as pd
from typing import Dict, Any, Optional
from hpc.slurm import generate_slurm_script, calculate_experiment_memory


def generate_experiment_py(config: Dict[str, Any]) -> str:
    """
    Generates a standalone, dependency-minimal Python script that:
    1. Loads dataset.csv & config.json
    2. Runs the exact preprocessing, model instantiation, validation/optimization
    3. Handles Random Forest hyperparameters, seed propagation, OOB scores, and multi-seed evaluation
    4. Serializes comprehensive results to results.json for Solvosys Results UI consumption.
    """
    script_template = """# ==========================================================
# Self-Contained Solvosys HPC Experiment Runner
# Generated by Solvosys Machine Learning Workbench
# ==========================================================

import json
import time
import os
import numpy as np
import pandas as pd

# Load configuration and dataset
with open('config.json', 'r', encoding='utf-8') as f:
    config = json.load(f)

df = pd.read_csv('dataset.csv')

features = config['features']
target = config['target']
problem_type = config['problem_type']
model_name = config['model_name']
split_method = config['split_method']
preprocessing = config.get('preprocessing', {})
hp = config.get('hyperparameters', {})
use_oob = config.get('use_oob', False)
use_multiple_seeds = config.get('use_multiple_seeds', False)
num_seeds = int(config.get('num_seeds', 5)) if use_multiple_seeds else 1
optimization = config.get('optimization', 'None')
opt_iters = int(config.get('opt_iters', 10))
opt_cv_folds = int(config.get('opt_cv', 3))

X = df[features]
y = df[target]

start_overall_time = time.time()

# 1. Preprocessing Pipeline Builder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler, RobustScaler

numeric_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

numeric_transformers = []
missing_strat = preprocessing.get('missing_strategy', 'None')
if missing_strat == 'Mean':
    numeric_transformers.append(('imputer', SimpleImputer(strategy='mean')))
elif missing_strat == 'Median':
    numeric_transformers.append(('imputer', SimpleImputer(strategy='median')))
elif missing_strat == 'Most Frequent':
    numeric_transformers.append(('imputer', SimpleImputer(strategy='most_frequent')))

scale_strat = preprocessing.get('scaling_strategy', 'None')
if scale_strat == 'StandardScaler':
    numeric_transformers.append(('scaler', StandardScaler()))
elif scale_strat == 'MinMaxScaler':
    numeric_transformers.append(('scaler', MinMaxScaler()))
elif scale_strat == 'RobustScaler':
    numeric_transformers.append(('scaler', RobustScaler()))

if not numeric_transformers:
    numeric_transformers.append(('passthrough', 'passthrough'))

num_pipeline = Pipeline(numeric_transformers)

cat_transformers = []
enc_strat = preprocessing.get('encoding_strategy', 'None')
if enc_strat == 'One-Hot':
    cat_transformers.append(('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False)))
elif enc_strat == 'Ordinal':
    cat_transformers.append(('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)))

if not cat_transformers:
    cat_transformers.append(('passthrough', 'passthrough'))

cat_pipeline = Pipeline(cat_transformers)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, numeric_features),
        ('cat', cat_pipeline, categorical_features)
    ],
    remainder='drop'
)

# 2. Model Factory
def create_model(seed=42):
    model_hp = hp.copy()
    model_hp['random_state'] = seed
    if model_name == 'Linear Regression':
        from sklearn.linear_model import LinearRegression
        return LinearRegression()
    elif model_name == 'Polynomial Regression':
        from sklearn.linear_model import LinearRegression
        from sklearn.preprocessing import PolynomialFeatures
        return Pipeline([('poly', PolynomialFeatures(degree=model_hp.get('degree', 2), include_bias=False)), ('linear', LinearRegression())])
    elif model_name == 'Lasso Regression':
        from sklearn.linear_model import Lasso
        return Lasso(alpha=model_hp.get('alpha', 1.0), max_iter=model_hp.get('max_iter', 1000), random_state=seed)
    elif model_name == 'Elastic Net':
        from sklearn.linear_model import ElasticNet
        return ElasticNet(alpha=model_hp.get('alpha', 1.0), l1_ratio=model_hp.get('l1_ratio', 0.5), max_iter=model_hp.get('max_iter', 1000), random_state=seed)
    elif model_name == 'Decision Tree':
        if problem_type == 'Regression':
            from sklearn.tree import DecisionTreeRegressor
            return DecisionTreeRegressor(random_state=seed, max_depth=model_hp.get('max_depth'), min_samples_split=model_hp.get('min_samples_split', 2), min_samples_leaf=model_hp.get('min_samples_leaf', 1))
        else:
            from sklearn.tree import DecisionTreeClassifier
            return DecisionTreeClassifier(random_state=seed, max_depth=model_hp.get('max_depth'), min_samples_split=model_hp.get('min_samples_split', 2), min_samples_leaf=model_hp.get('min_samples_leaf', 1))
    elif model_name == 'Random Forest':
        if problem_type == 'Regression':
            from sklearn.ensemble import RandomForestRegressor
            return RandomForestRegressor(
                n_estimators=model_hp.get('n_estimators', 100),
                max_depth=model_hp.get('max_depth'),
                min_samples_split=model_hp.get('min_samples_split', 2),
                min_samples_leaf=model_hp.get('min_samples_leaf', 1),
                max_features=model_hp.get('max_features', 'sqrt'),
                max_samples=model_hp.get('max_samples'),
                min_impurity_decrease=model_hp.get('min_impurity_decrease', 0.0),
                bootstrap=True if use_oob else model_hp.get('bootstrap', True),
                oob_score=True if use_oob else model_hp.get('oob_score', False),
                random_state=seed
            )
        else:
            from sklearn.ensemble import RandomForestClassifier
            return RandomForestClassifier(
                n_estimators=model_hp.get('n_estimators', 100),
                max_depth=model_hp.get('max_depth'),
                min_samples_split=model_hp.get('min_samples_split', 2),
                min_samples_leaf=model_hp.get('min_samples_leaf', 1),
                max_features=model_hp.get('max_features', 'sqrt'),
                max_samples=model_hp.get('max_samples'),
                min_impurity_decrease=model_hp.get('min_impurity_decrease', 0.0),
                bootstrap=True if use_oob else model_hp.get('bootstrap', True),
                oob_score=True if use_oob else model_hp.get('oob_score', False),
                random_state=seed
            )
    elif model_name == 'XGBoost Regressor':
        from xgboost import XGBRegressor
        return XGBRegressor(random_state=seed)
    elif model_name == 'CatBoost Regressor':
        from catboost import CatBoostRegressor
        return CatBoostRegressor(random_seed=seed, verbose=0)
    elif model_name == 'Logistic Regression':
        from sklearn.linear_model import LogisticRegression
        return LogisticRegression(max_iter=1000)
    elif model_name == 'XGBoost Classifier':
        from xgboost import XGBClassifier
        return XGBClassifier(random_state=seed)
    elif model_name == 'CatBoost Classifier':
        from catboost import CatBoostClassifier
        return CatBoostClassifier(random_seed=seed, verbose=0)
    raise ValueError(f'Unknown model: {model_name}')

# 3. Execution & Metrics
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, RandomizedSearchCV, GridSearchCV

def run_single_seed(seed=42):
    train_pct = config.get('train_percent', 80) / 100.0
    
    if split_method == 'Train-Test Split':
        X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_pct, random_state=seed)
    else:
        X_train, X_test, y_train, y_test = X, X, y, y

    base_model = create_model(seed=seed)
    pipeline = Pipeline([('preprocessor', preprocessor), ('model', base_model)])
    
    best_params = None
    best_cv_score = None
    
    if optimization != 'None' and split_method == 'Train-Test Split':
        param_dist = {}
        if model_name == 'Random Forest':
            param_dist = {
                'model__n_estimators': [50, 100, 200, 300],
                'model__max_depth': [None, 5, 10, 20, 30],
                'model__min_samples_split': [2, 5, 10],
                'model__min_samples_leaf': [1, 2, 4],
                'model__max_features': ['sqrt', 'log2', None]
            }
        elif model_name == 'Decision Tree':
            param_dist = {
                'model__max_depth': [None, 3, 5, 10, 20],
                'model__min_samples_split': [2, 5, 10],
                'model__min_samples_leaf': [1, 2, 4]
            }
            
        if param_dist:
            cv = KFold(n_splits=opt_cv_folds, shuffle=True, random_state=seed)
            if optimization == 'Grid Search':
                search = GridSearchCV(pipeline, param_grid=param_dist, cv=cv, scoring='r2' if problem_type == 'Regression' else 'accuracy', n_jobs=-1)
            else:
                search = RandomizedSearchCV(pipeline, param_distributions=param_dist, n_iter=opt_iters, cv=cv, scoring='r2' if problem_type == 'Regression' else 'accuracy', random_state=seed, n_jobs=-1)
            search.fit(X_train, y_train)
            pipeline = search.best_estimator_
            best_params = search.best_params_
            best_cv_score = float(search.best_score_)
        else:
            pipeline.fit(X_train, y_train)
    else:
        pipeline.fit(X_train, y_train)

    y_train_pred = pipeline.predict(X_train)
    y_test_pred = pipeline.predict(X_test)
    
    metrics = {}
    train_metrics = {}
    if problem_type == 'Regression':
        metrics['R2 Score'] = float(r2_score(y_test, y_test_pred))
        metrics['RMSE'] = float(np.sqrt(mean_squared_error(y_test, y_test_pred)))
        metrics['MAE'] = float(mean_absolute_error(y_test, y_test_pred))
        metrics['MAPE'] = float(mean_absolute_percentage_error(y_test, y_test_pred) * 100)

        train_metrics['R2 Score'] = float(r2_score(y_train, y_train_pred))
        train_metrics['RMSE'] = float(np.sqrt(mean_squared_error(y_train, y_train_pred)))
        train_metrics['MAE'] = float(mean_absolute_error(y_train, y_train_pred))
        train_metrics['MAPE'] = float(mean_absolute_percentage_error(y_train, y_train_pred) * 100)
    else:
        metrics['Accuracy'] = float(accuracy_score(y_test, y_test_pred))
        metrics['Precision'] = float(precision_score(y_test, y_test_pred, average='weighted', zero_division=0))
        metrics['Recall'] = float(recall_score(y_test, y_test_pred, average='weighted', zero_division=0))
        metrics['F1 Score'] = float(f1_score(y_test, y_test_pred, average='weighted', zero_division=0))

        train_metrics['Accuracy'] = float(accuracy_score(y_train, y_train_pred))
        train_metrics['Precision'] = float(precision_score(y_train, y_train_pred, average='weighted', zero_division=0))
        train_metrics['Recall'] = float(recall_score(y_train, y_train_pred, average='weighted', zero_division=0))
        train_metrics['F1 Score'] = float(f1_score(y_train, y_train_pred, average='weighted', zero_division=0))

    oob_score_val = None
    fitted_model = pipeline.named_steps['model']
    if hasattr(fitted_model, 'oob_score_') and fitted_model.oob_score_ is not None:
        oob_score_val = float(fitted_model.oob_score_)
        metrics['OOB Score'] = oob_score_val

    # Feature importances
    feature_importances = []
    if hasattr(fitted_model, 'feature_importances_'):
        for f, imp in zip(features, fitted_model.feature_importances_):
            feature_importances.append({'feature': f, 'importance': float(imp)})
        feature_importances = sorted(feature_importances, key=lambda x: x['importance'], reverse=True)

    return {
        'pipeline': pipeline,
        'metrics': metrics,
        'train_metrics': train_metrics,
        'X_train': X_train,
        'X_test': X_test,
        'y_train': y_train,
        'y_test': y_test,
        'y_test_pred': y_test_pred,
        'oob_score': oob_score_val,
        'best_params': best_params,
        'best_cv_score': best_cv_score,
        'feature_importances': feature_importances
    }

# 4. Multi-seed loop or Single run
initial_seed = int(config.get('random_state', 42))
if use_multiple_seeds and num_seeds > 1:
    all_metrics = []
    final_res = None
    for i in range(num_seeds):
        current_seed = initial_seed + i
        res = run_single_seed(seed=current_seed)
        all_metrics.append(res['metrics'])
        final_res = res

    aggregated_metrics = {}
    for k in all_metrics[0].keys():
        vals = [m[k] for m in all_metrics if k in m and m[k] is not None]
        if vals:
            aggregated_metrics[k] = {
                'mean': float(np.mean(vals)),
                'std': float(np.std(vals))
            }
    primary_res = final_res
    final_metrics = aggregated_metrics
else:
    primary_res = run_single_seed(seed=initial_seed)
    final_metrics = primary_res['metrics']

training_time = time.time() - start_overall_time

# 5. Build Prediction Preview DataFrame for UI (Top 20 rows)
y_test_arr = np.array(primary_res['y_test'])
y_pred_arr = np.array(primary_res['y_test_pred'])
preview_rows = []
limit = min(20, len(y_test_arr))

for i in range(limit):
    act = float(y_test_arr[i]) if problem_type == 'Regression' else str(y_test_arr[i])
    pred = float(y_pred_arr[i]) if problem_type == 'Regression' else str(y_pred_arr[i])
    row_dict = {'Index': i + 1, 'Actual': act, 'Predicted': pred}
    if problem_type == 'Regression':
        res = act - pred
        abs_res = abs(res)
        pct_err = (abs_res / abs(act) * 100.0) if act != 0 else 0.0
        row_dict['Residual'] = round(res, 4)
        row_dict['Abs Residual'] = round(abs_res, 4)
        row_dict['% Error'] = round(pct_err, 2)
    preview_rows.append(row_dict)

# 6. Build Final Serialized Results JSON
def extract_scalar_metric(m_dict, key):
    val = m_dict.get(key) if isinstance(m_dict, dict) else None
    if isinstance(val, dict) and 'mean' in val:
        return float(val['mean'])
    return float(val) if val is not None else None

training_r2_val = extract_scalar_metric(primary_res['train_metrics'], 'R2 Score') if problem_type == 'Regression' else None
validation_r2_val = extract_scalar_metric(final_metrics, 'R2 Score') if problem_type == 'Regression' else None
rmse_val = extract_scalar_metric(final_metrics, 'RMSE') if problem_type == 'Regression' else None
mae_val = extract_scalar_metric(final_metrics, 'MAE') if problem_type == 'Regression' else None
mape_val = extract_scalar_metric(final_metrics, 'MAPE') if problem_type == 'Regression' else None
training_acc_val = extract_scalar_metric(primary_res['train_metrics'], 'Accuracy') if problem_type == 'Classification' else None
validation_acc_val = extract_scalar_metric(final_metrics, 'Accuracy') if problem_type == 'Classification' else None

results_payload = {
    'status': 'completed',
    'execution_mode': 'hpc',
    'training_time': round(float(training_time), 3),
    'problem_type': problem_type,
    'model_name': model_name,
    'metrics': final_metrics,
    'train_metrics': primary_res['train_metrics'],
    'training_r2': training_r2_val,
    'validation_r2': validation_r2_val,
    'rmse': rmse_val,
    'mae': mae_val,
    'mape': mape_val,
    'training_accuracy': training_acc_val,
    'validation_accuracy': validation_acc_val,
    'feature_importances': primary_res['feature_importances'],
    'predictions_preview': preview_rows,
    'y_test': [float(v) for v in y_test_arr] if problem_type == 'Regression' else [str(v) for v in y_test_arr],
    'y_pred': [float(v) for v in y_pred_arr] if problem_type == 'Regression' else [str(v) for v in y_pred_arr],
    'y_test_pred': [float(v) for v in y_pred_arr] if problem_type == 'Regression' else [str(v) for v in y_pred_arr],
    'oob_score': primary_res['oob_score'],
    'best_params': primary_res['best_params'],
    'best_cv_score': primary_res['best_cv_score'],
    'evaluation_config': {
        'validation': f"{split_method} ({config.get('train_percent', 80)}/{100 - config.get('train_percent', 80)})" if split_method == 'Train-Test Split' else split_method,
        'optimization': optimization if optimization != 'None' else 'None',
        'random_state': initial_seed,
        'oob': use_oob,
        'features_count': len(features),
        'rows_count': len(df),
        'execution_mode': 'hpc'
    },
    'available_plots': [
        'Actual vs Predicted',
        'Residual Plot',
        'Residuals Distribution',
        'QQ Plot',
        'Feature Importance'
    ] if problem_type == 'Regression' else [
        'Confusion Matrix',
        'Feature Importance'
    ]
}

with open('results.json', 'w', encoding='utf-8') as f:
    json.dump(results_payload, f, indent=2)

print(f'HPC Experiment Finished successfully in {training_time:.2f}s. Results written to results.json')
"""
    return script_template.replace("\r\n", "\n").replace("\r", "\n") + "\n"


def sanitize_config(config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Sanitizes experiment configuration to ensure:
    1. Complete reproduction parameters exist.
    2. ZERO credentials, passwords, passphrases, or private keys are serialized.
    3. JSON serializability.
    """
    allowed_keys = [
        "dataset_id", "target", "target_name", "target_unit", "features",
        "problem_type", "model_name", "hyperparameters", "split_method",
        "train_percent", "folds", "repeats", "optimization", "opt_iters",
        "opt_cv", "use_multiple_seeds", "num_seeds", "use_oob",
        "preprocessing", "random_state", "partition"
    ]
    sanitized = {}
    for k in allowed_keys:
        if k in config:
            sanitized[k] = config[k]

    # Ensure baseline defaults
    sanitized.setdefault("problem_type", "Regression")
    sanitized.setdefault("model_name", "Random Forest")
    sanitized.setdefault("split_method", "Train-Test Split")
    sanitized.setdefault("train_percent", 80)
    sanitized.setdefault("optimization", "None")
    sanitized.setdefault("use_multiple_seeds", False)
    sanitized.setdefault("use_oob", False)
    sanitized.setdefault("random_state", 42)
    sanitized.setdefault("hyperparameters", {})
    sanitized.setdefault("preprocessing", {
        "missing_strategy": "None",
        "encoding_strategy": "None",
        "scaling_strategy": "None"
    })

    return sanitized


def package_experiment(
    df: pd.DataFrame,
    config: Dict[str, Any],
    output_dir: Optional[str] = None,
    partition: Optional[str] = None,
    time_limit: str = "00:10:00",
    cpus_per_task: int = 2,
    mem: str = "2G",
    gpus: int = 0
) -> str:
    """
    Creates a self-contained HPC experiment workspace bundle containing:
    - dataset.csv
    - config.json (sanitized, zero credentials)
    - experiment.py (pure Unix LF)
    - run.slurm (pure Unix LF with explicit memory allocation)

    Returns the absolute path to the local bundle directory.
    """
    if not output_dir:
        workspace_id = f"solvosys_hpc_pkg_{uuid.uuid4().hex[:12]}"
        output_dir = os.path.join(tempfile.gettempdir(), workspace_id)

    os.makedirs(output_dir, exist_ok=True)

    # 1. Write dataset.csv
    dataset_path = os.path.join(output_dir, "dataset.csv")
    df.to_csv(dataset_path, index=False)

    # 2. Write sanitized config.json
    clean_config = sanitize_config(config)
    if partition:
        clean_config["partition"] = partition
    config_path = os.path.join(output_dir, "config.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(clean_config, f, indent=2)

    # 3. Write experiment.py with strictly Unix LF line endings (binary mode write)
    exp_script = generate_experiment_py(clean_config)
    exp_path = os.path.join(output_dir, "experiment.py")
    with open(exp_path, "wb") as f:
        f.write(exp_script.encode("utf-8"))

    # 4. Write run.slurm with strictly Unix LF line endings (binary mode write)
    target_partition = partition or clean_config.get("partition")
    job_name = f"solvosys_{clean_config.get('model_name', 'exp').replace(' ', '_').lower()}"
    
    slurm_script = generate_slurm_script(
        job_name=job_name,
        time_limit=time_limit,
        cpus_per_task=cpus_per_task,
        mem=mem,
        gpus=gpus,
        partition=target_partition
    )
    slurm_path = os.path.join(output_dir, "run.slurm")
    with open(slurm_path, "wb") as f:
        f.write(slurm_script.encode("utf-8"))

    return output_dir
