"""
Module for bundling experiment artifacts into a single ZIP archive.
"""

import io
import os
import tempfile
import zipfile
from typing import Dict, Any

import numpy as np
import pandas as pd
import sklearn
import matplotlib
import seaborn

from export.export_utils import ExportContext, find_plot_file
from export.code_generator import generate_python_script
from export.csv_export import export_predictions_to_dataframe
from export.pdf_generator import generate_pdf_report


def generate_readme(context: ExportContext) -> str:
    """
    Generate a README markdown string for the ZIP bundle.

    Args:
        context (ExportContext): The export context.

    Returns:
        str: Markdown README text.
    """
    config = context.config
    results = context.results
    model_name = config.get("model_name", "Model")
    problem_type = config.get("problem_type", "Task")
    dataset_name = results.get("dataset", "dataset.csv")

    readme = f"""# ML Studio Experiment Reproduction Bundle

This zip archive contains all the artifacts necessary to reproduce and review your machine learning experiment.

## Contents
1. `run_experiment.py`: Standalone Python script that replicates the data loading, preprocessing, model training, evaluation, and plot generation.
2. `predictions.csv`: CSV file containing the actual values, predictions, and residuals/probabilities on the test set.
3. `report.pdf`: Academic-quality PDF report summarizing the dataset, preprocessing, hyperparameters, metrics, and plots.
4. Plots (PNG images): The visualization plots generated during model evaluation.
5. `requirements.txt`: Python package requirements to run the standalone script locally.

## Setup & Reproduction Instructions
1. Extract all files in this ZIP archive to a folder on your computer.
2. Ensure that your dataset CSV file is placed in the same folder and named `{dataset_name}`.
3. Install the required Python packages:
   ```bash
   pip install -r requirements.txt
   ```
4. Run the standalone script:
   ```bash
   python run_experiment.py
   ```

---
*Generated by ML Studio Workbench*
*Model Name: {model_name}*
*Task Type: {problem_type}*
"""
    return readme


def generate_requirements() -> str:
    """
    Generate requirements.txt string dynamically using active module versions.

    Returns:
        str: requirements.txt content.
    """
    reqs = [
        f"numpy=={np.__version__}",
        f"pandas=={pd.__version__}",
        f"scikit-learn=={sklearn.__version__}",
        f"matplotlib=={matplotlib.__version__}",
        f"seaborn=={seaborn.__version__}",
    ]
    return "\n".join(reqs) + "\n"


def generate_experiment_zip(context: ExportContext) -> io.BytesIO:
    """
    Generate a ZIP archive in-memory containing all experiment artifacts:
    Python script, prediction CSV, PDF report, README, requirements.txt, and plots.

    Args:
        context (ExportContext): The export context.

    Returns:
        io.BytesIO: A bytes buffer containing the ZIP archive data.
    """
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # 1. Add README.md
        readme_content = generate_readme(context)
        zip_file.writestr("README.md", readme_content)

        # 2. Add requirements.txt
        reqs_content = generate_requirements()
        zip_file.writestr("requirements.txt", reqs_content)

        # 3. Add Standalone Python Script
        script_content = generate_python_script(context)
        zip_file.writestr("run_experiment.py", script_content)

        # 4. Add Prediction CSV
        pred_df = export_predictions_to_dataframe(context)
        csv_buffer = io.StringIO()
        pred_df.to_csv(csv_buffer, index=False)
        zip_file.writestr("predictions.csv", csv_buffer.getvalue())

        # 5. Add PDF Report (via a temporary file)
        temp_dir = tempfile.gettempdir()
        temp_pdf_path = os.path.join(temp_dir, "report.pdf")
        try:
            generate_pdf_report(context, temp_pdf_path)
            with open(temp_pdf_path, "rb") as pdf_file:
                zip_file.writestr("report.pdf", pdf_file.read())
        finally:
            if os.path.exists(temp_pdf_path):
                os.remove(temp_pdf_path)

        # 6. Add Plots (embed any matching plots found in outputs or current directory)
        problem_type = context.config.get("problem_type")
        if problem_type == "Regression":
            plot_names = [
                "Actual vs Predicted",
                "Residual Plot",
                "Residual Distribution",
                "Prediction Error",
                "Feature Importance"
            ]
        else:
            plot_names = [
                "Confusion Matrix",
                "ROC Curve",
                "Precision-Recall Curve",
                "Feature Importance"
            ]

        for name in plot_names:
            img_path = find_plot_file(name)
            if img_path:
                filename = os.path.basename(img_path)
                with open(img_path, "rb") as img_file:
                    zip_file.writestr(filename, img_file.read())

    zip_buffer.seek(0)
    return zip_buffer
